### ISSUE TITLE
WavesKeeper not creating Waves object on local pages

### ISSUE THREAD

**Issue by bvk680** [wavesplatform/waveskeeper#25]
When I tested the waves keeper API I didn't get it to work at first and all I did was copy some example code that I found, after uploading it online to a server the same code worked. But when it is a local file it doesn't. I'll include the local files and would also like to add that I am on linux, I'm not shure if that has anything to do with it.
[index.css.txt](https://github.com/wavesplatform/waveskeeper/files/2672949/index.css.txt)
[main2.js.txt](https://github.com/wavesplatform/waveskeeper/files/2672950/main2.js.txt)
[waveskeepertest.html.txt](https://github.com/wavesplatform/waveskeeper/files/2672951/waveskeepertest.html.txt)

**Comment by vba2000** [comment]
Hello. Extension work only with http/https protocol. You need run this html page by simple http server. 
EXAMPLE:  Open terminal and run:  python -m SimpleHTTPServer 8000. Open in browser 127.0.0.1:8000
