### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by RaimanElshan** [wavesplatform/waveskeeper#30]
Step:
1) npm install
2) npm run start
![image](https://user-images.githubusercontent.com/22689890/51532413-18df9180-1e51-11e9-90d6-b57f202de1d2.png)
![image](https://user-images.githubusercontent.com/22689890/51532432-23019000-1e51-11e9-89d5-f89d6f96801f.png)

OriginController not found in directory
How to solve the problem and run?

**Comment by vba2000** [comment]
Hello. Merge last release version to master. Thanks for issue.
