### ISSUE TITLE
Wallet button points to obsolete client

### ISSUE THREAD

**Issue by sunchaser68** [wavesplatform/waveskeeper#80]
**Describe the bug**
Clicking on button WALLET in Waves Keeper forwards to the obsolete client. Please change it to waves.exchange.

**To Reproduce**
1.  Enter WAVES Keeper
2. Click on 'Wallet'
3. You are redirected to obsolete client

**Expected behavior**
Should redirect to waves.exchange.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WINDOWS 10
 - Browser: Bravo
 - Version: Version 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)

**Comment by vba2000** [comment]
Release 1.1.12 - fix this bug

**Comment by crypto-supporter** [comment]
@vba2000 when will you release 1.1.12? IMO this should have been released 4-5 days ago as a quick fix, when the issue first appeared. How do your release cycles look like?
