### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Praexor** [wavesplatform/waveskeeper#85]
Keeper does not accept this network matcher https://testnet.waves.exchange/api/v1/forward/matcher/matcher

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Debian/Ubuntu/iOS]
 - Browser/JVM [e.g. chrome, safari]

**Additional context**

**Comment by tsigel** [comment]
> Keeper does not accept this network matcher https://testnet.waves.exchange/api/v1/forward/matcher/matcher

This is not matcher url. Matcher url for testnet is "https://matcher-testnet.waves.exchange/matcher".
